### ISSUE TITLE
Use similar configurations for our blogs

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/docs.carpentries.org#146]
There are some differences in the way the `_config.yml` file is written for the SWC and the DC websites, leading to differences in the YAML that is required and where to put the files when writing a blog post. Given that both websites are using the same Jekyll template, there is no reason for this. I'd like to suggest we harmonize the configuration of both sites (mainly making the DC configuration look like the SWC one) so that there is a single section on how to contribute a blog post in the handbook.

This would mean that we'd need to setup redirections on existing DC blog posts to match the permalink structure used by SWC blog posts.

I haven't been part of conversations regarding which template to use for the carpentries.org site, but to avoid having to keep documentation for another template, I'm wondering if we also shouldn't consider using the template we use for SWC and DC for the carpentries.org site.

This is also related to #82 which would become moot if we harmonized configuration of the SWC and DC sites.

**Comment by maneesha** [comment]
Want to be sure @weaverbel is involved this this

**Comment by weaverbel** [comment]
@fmichonneau @maneesha We should have a proper discussion about the website so everyone understands why it is the way it is and how we got here.

The original plan was for the website to be a small, mainly 'pass-through' site that would be OK to launch as an interim site while we figured out what we needed for a new merged Carpentries website. We picked the agency template because it was suited to that kind of minimal web presence. It required a lot of tweaking to even add a blog to that template though and it's been a bit of a headache. If this is to be the final site then I don't think the agency template is suitable and I would be happy to migrate out of it as trying to rework it for what is needed would be a lot of work. 

However what I think @tracykteal wanted was for this to be an interim, minimally viable website, with the idea that we engage someone external to build the final website for us down the track once we have decided what we want and we understand how all the existing pieces like the handbook and the FAQs fit together. If that is still the case, then migrating the existing site to a different template might be a lot of work for no real benefit if we are moving later anyway. 

We should really make a firm decision one way or another or this will all just drag on forever. What I have tried to put out there is the minimum viable product and no more.

**Comment by tracykteal** [comment]
Yes, having this be a smaller website with links to the handbook and information on the SWC/DC/LC pages is still a good plan!

This might not be the final website, but it will still be around for several months at a minimum, and we know that short term often turns into longer term. If this template isn't working, then we should switch. It sounds like some time now could save headaches and more time even down the short-term road. @weaverbel I sent you an email, so can follow up with you on what you would recommend. Since we do have much of the content generated already (thank you!) with a template switch, we could just move much of the text over to a new template, so don't have to regenerate content. Belinda and I will follow up on plans once we've had a chance to discuss.

**Comment by maneesha** [comment]
@fmichonneau Is this something that's about the handbook or about the blogs across all four websites?  We have had other conversations about having all four websites using the same template. I believe it's only SWC that uses a different template, so can we close this here and discuss it in SWC or offline as a bigger project?

**Comment by fmichonneau** [comment]
I had opened the issue here because of the documentation aspect but we could keep the discussion somewhere else. The 4 websites use the same template (with SWC using a simplified version) but they are not set up the same way which lead to a need for different options to set in the YAML headers of blog posts and pages. Ideally, we'd want to use the same template and configuration across all our sites to facilitate maintenance.

**Comment by maneesha** [comment]
@fmichonneau  Do you want to keep this open here?

**Comment by fmichonneau** [comment]
yes, this has been mostly addressed, and our other blogs are rarely used.
