### ISSUE TITLE
Front page has two first-level headings

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/docs.carpentries.org#271]
For web accessibility, it is generally expected that a page has only one first-level (`<h1>`) heading (see https://webaim.org/techniques/headings/ for example). The landing page currently has two: "Popular Resources" and "Quick Links". Can we bump them both down to `h2`?

**Comment by OscarSiba** [comment]
Thanks for this @tobyhodges. Happy for us to do so.

Also, @maneesha can we please rename "Popular Resources" to "Highlighted Resources". That's a more accurate label for that section.

**Comment by maneesha** [comment]
Thanks for this resource @tobyhodges. I was not aware of the "only one H1" recommendation.  
As this page has two equal headings, they are both treated as H1 because they are the highest level headings.  H2 without H1 would be cause another accessibility concern.

I have put in PR #272 to add in an H1 which forces the others to be H2.

**Comment by tobyhodges** [comment]
> As this page has two equal headings, they are both treated as H1 because they are the highest level headings. H2 without H1 would be cause another accessibility concern.

Thanks for this context. I can see I have plenty more to learn about Sphinx and restructured text 😆

**Comment by maneesha** [comment]
Closed with #272
