### ISSUE TITLE
consider renaming the master branch

### ISSUE THREAD

**Issue by serahrono** [carpentries/docs.carpentries.org#626]
Scott Hanselman offers a how-to guide for this in his blog post https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx, and if @maneesha agrees, I will go ahead and do this.

**Comment by serahrono** [comment]
@fmichonneau what do you think? might be good to discuss this more broadly and see what guidelines to offer for all repositories in The Carpentries organisation on GitHub

**Comment by maneesha** [comment]
hi @serahrono , thanks so much for bringing this up. It means so much to me to remove this terminology from spaces like this. Can you share a bit about why you'd like to prioritize re-naming this branch in this repo?  I'm including some follow up questions here just as record, but this applies to all Carpentries repos I may continue this discussion in another space.

I think re-naming just this one branch in this one repo without doing anything else  may cause confusion.  Anecdotally, this solution also may break sites built on github pages (as some of our other sites are).  I'd like to talk about this with @fmichonneau  so that we can plan to:

* Identify all repos that have a master branch in any of our organization
* Re-name them (figuring out what to do with github pages)
* Identify all documentation within each repo that references a master branch and update that
* Identify all places in our lessons that reference a master branch and update those
* Build a communication plan around why we are doing all this, including identifying naming conventions as we move ahead

**Comment by fmichonneau** [comment]
Thanks for bringing this up @serahrono. I'm in support of removing this terminology from our repositories (it's something that has bothered me for a while). As @maneesha pointed out, a lot of our infrastructure (scripts, documentation, ...) relies on the assumption on the current terminology used for the default branch. Some are within our control but others might not be.  I'll consult with the Executive Team and with @maneesha later this week to figure out what could be a good plan of action to implement this change.

**Comment by zkamvar** [comment]
For what it's worth, people have begun to write tools for auto-migrating repositories: https://github.com/dfm/rename-github-default-branch

Unfortunately, this will break any website that doesn't have the `gh-pages` branch as the default branch. I tried this with my dissertation repo and found that @github only allows the "master" or "gh-pages" branch for the site. 

![Screenshot showing a dropdown menu from GitHub Pages with three options for the source of the website, master branch, master branch docs folder, or none](https://user-images.githubusercontent.com/3639446/84676417-57606b00-aee2-11ea-8a54-677063dab542.png)

**Comment by zkamvar** [comment]
Note: I just received feedback from GitHub about allowing the default branch to be the source for gh pages:

> Thanks for writing in! While GitHub does not currently allow setting a custom default branch for Pages, I can confirm that the team is looking at ways to replace master as the default branch name across the board.
> 
> Our roadmap is not publicly visible, so we recommend that you keep an eye on the GitHub Blog for the latest announcements about new features.
> 
> In the meantime, please let us know if there is anything else we can do for you and we will be happy to assist!

**Comment by serahrono** [comment]
hey @fmichonneau, maybe we can revisit this at some point over the next few weeks?

**Comment by fmichonneau** [comment]
yes, we have started to transition some of our repos where possible. I just created the main branch and updated the scripts that build the site to use it. I'll change the default branch to `main` but I'll let @maneesha delete `master` if she agrees to the change for this repo.

**Comment by serahrono** [comment]
thank you so much @fmichonneau and @maneesha, @kmomar asked about this in our Community Development Team meeting today, and will be happy to see this is happening

**Comment by maneesha** [comment]
The `master` branch has been renamed to `main`.
