### ISSUE TITLE
Broken link to logos

### ISSUE THREAD

**Issue by ageorgou** [carpentries/docs.carpentries.org#821]
In the [new policy](https://docs.carpentries.org/topic_folders/communications/resources/logos.html), the link to the Software Carpentry logos is currently broken: it points to [the `main` branch](https://github.com/swcarpentry/communications/tree/main/misc/logo), whereas that repository only has [`master`](https://github.com/swcarpentry/communications/tree/master/misc/logo).

I didn't open a pull request because I wasn't sure whether there were any plans to rename that branch, but happy to!

**Comment by maneesha** [comment]
Thanks for bringing this up @ageorgou 

We have been renaming our branches from `master` to `main`.  In some cases, this is not so straightforward because branch names were tied to external workflows.  I don't think that's the case here; it should be fine to re-name that branch so I can make the change.  @fmichonneau  can you confirm?

**Comment by fmichonneau** [comment]
Thank you for noticing this @ageorgou! I renamed the branch on the SWC repo and the link now works.
