### ISSUE TITLE
Slack instructions update?

### ISSUE THREAD

**Issue by karenword** [carpentries/docs.carpentries.org#928]
Two things of note re Slack instructions:
1. The instructions for browsing channels are not current for my Slack app (there is no "+" next to Channels, and "Browse channels" is in a secondary menu after "Manage."). Is this a place where linking to Slack documentation might be more sustainable?
2. I did not find what I was looking for, which was instructions for updating an email address. It does not seem to be possible for the user to do this themselves.

**Comment by maneesha** [comment]
Tagging @acrall for some feedback about this. I would recommend directing all slack information to slack's own documentation rather than us trying to keep our own slack documentation up to date.  Is there anything in the Slack section you'd want to explicitly see in our handbook?
https://docs.carpentries.org/topic_folders/communications/tools/slack-and-email.html#slack-quick-start-guide

Also note that users can update their own email address.  See https://slack.com/help/articles/207262907-Change-your-email-address

**Comment by maneesha** [comment]
Reminder @acrall

**Comment by acrall** [comment]
@maneesha @karenword We can remove this for now as I have not had time to update it and need to add it to my workflow. I did this shortly after starting to work here, and I know the images I had originally included did not get added. But, generally, a quick start guide is to support onboarding our community members to a new platform and directs them to the information they most need to know to get started. Navigating all the information in the user's guide can be intimidating so this allows us to highlight the most important features and provides some information about how our community uses the space (e.g. naming conventions for channels). So, I still think it is a valuable resource and will return to it at a later time

**Comment by acrall** [comment]
I realised this resource is linked to in all of our Welcome Session tip sheets. I will review and make updates now and include a quarterly review in my workflow to review and update as needed. Once I have made edits, I will link to the pull request here to see if this issue can be closed.

**Comment by acrall** [comment]
@maneesha Addressed by [934](https://github.com/carpentries/docs.carpentries.org/pull/934)

**Comment by maneesha** [comment]
Closing this as noted above this was addressed
